FROM golang:1.26.4-trixie AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o /seed ./scripts/seed

FROM golang:1.26.4-alpine
WORKDIR /app
COPY --from=build /seed /seed

ENTRYPOINT [ "/seed" ]
