FROM golang:1.26.4-trixie AS build
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

FROM debian:trixie-slim
COPY --from=build /go/bin/goose /usr/local/bin/goose

WORKDIR /app
COPY migrations ./migrations

ENTRYPOINT ["goose"]