// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listUsersWithVotes = `-- name: ListUsersWithVotes :many
SELECT u.id, u.idp_sub, u.created_at, COUNT(*) AS votes
FROM users u
JOIN votes v ON u.id = v.user_id
WHERE u.id > $1
GROUP BY u.id, u.idp_sub, u.created_at
ORDER BY u.id
LIMIT $2
`

type ListUsersWithVotesParams struct {
	ID    uuid.UUID
	Limit int32
}

type ListUsersWithVotesRow struct {
	ID        uuid.UUID
	PidSub    string
	CreatedAt time.Time
	Votes     int64
}

func (q *Queries) ListUsersWithVotes(ctx context.Context, arg ListUsersWithVotesParams) ([]ListUsersWithVotesRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithVotes, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersWithVotesRow
	for rows.Next() {
		var i ListUsersWithVotesRow
		if err := rows.Scan(
			&i.ID,
			&i.PidSub,
			&i.CreatedAt,
			&i.Votes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
