// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
WITH expired_sessions AS (
    SELECT id FROM sessions
    WHERE expires_at < CURRENT_TIMESTAMP
    LIMIT 5000
    FOR UPDATE SKIP LOCKED
)
DELETE FROM sessions WHERE id IN (SELECT id FROM expired_sessions)
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :execrows
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, token_hash, user_id, access_token, access_token_expires_at, refresh_token, id_token, scopes, ip_address, user_agent, roles, created_at, last_seen_at, expires_at FROM sessions WHERE token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.AccessToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshToken,
		&i.IDToken,
		&i.Scopes,
		&i.IPAddress,
		&i.UserAgent,
		&i.Roles,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, idp_sub, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.PidSub, &i.CreatedAt)
	return i, err
}

const getUserBySub = `-- name: GetUserBySub :one
SELECT id, idp_sub, created_at FROM users WHERE idp_sub = $1
`

func (q *Queries) GetUserBySub(ctx context.Context, idpSub string) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySub, idpSub)
	var i User
	err := row.Scan(&i.ID, &i.PidSub, &i.CreatedAt)
	return i, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (
    token_hash, user_id, access_token, access_token_expires_at, refresh_token,
    id_token, scopes, ip_address, user_agent, roles, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type InsertSessionParams struct {
	TokenHash            []byte
	UserID               uuid.UUID
	AccessToken          []byte
	AccessTokenExpiresAt *time.Time
	RefreshToken         []byte
	IDToken              []byte
	Scopes               *string
	IPAddress            netip.Addr
	UserAgent            *string
	Roles                []string
	ExpiresAt            time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.TokenHash,
		arg.UserID,
		arg.AccessToken,
		arg.AccessTokenExpiresAt,
		arg.RefreshToken,
		arg.IDToken,
		arg.Scopes,
		arg.IPAddress,
		arg.UserAgent,
		arg.Roles,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertSessionEvent = `-- name: InsertSessionEvent :one
INSERT INTO session_events (session_id, idp_sub, event, ip_address)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at
`

type InsertSessionEventParams struct {
	SessionID uuid.UUID
	PidSub    string
	Event     string
	IPAddress netip.Addr
}

type InsertSessionEventRow struct {
	ID        int64
	CreatedAt time.Time
}

func (q *Queries) InsertSessionEvent(ctx context.Context, arg InsertSessionEventParams) (InsertSessionEventRow, error) {
	row := q.db.QueryRow(ctx, insertSessionEvent,
		arg.SessionID,
		arg.PidSub,
		arg.Event,
		arg.IPAddress,
	)
	var i InsertSessionEventRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (idp_sub) VALUES ($1)
ON CONFLICT (idp_sub) DO UPDATE SET idp_sub = EXCLUDED.idp_sub
RETURNING id, created_at
`

type UpsertUserRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) UpsertUser(ctx context.Context, idpSub string) (UpsertUserRow, error) {
	row := q.db.QueryRow(ctx, upsertUser, idpSub)
	var i UpsertUserRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
