// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package dbgen

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const updateFilmRatings = `-- name: UpdateFilmRatings :batchone
UPDATE films SET rating = $1 WHERE id = $2 RETURNING id
`

type UpdateFilmRatingsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpdateFilmRatingsParams struct {
	Rating float64
	ID     int32
}

func (q *Queries) UpdateFilmRatings(ctx context.Context, arg []UpdateFilmRatingsParams) *UpdateFilmRatingsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Rating,
			a.ID,
		}
		batch.Queue(updateFilmRatings, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpdateFilmRatingsBatchResults{br, len(arg), false}
}

func (b *UpdateFilmRatingsBatchResults) QueryRow(f func(int, int32, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var id int32
		if b.closed {
			if f != nil {
				f(t, id, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&id)
		if f != nil {
			f(t, id, err)
		}
	}
}

func (b *UpdateFilmRatingsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
