// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: duels.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const composeDuel = `-- name: ComposeDuel :one
WITH winner AS (
    SELECT rating FROM films WHERE films.id = $1
),
in_window AS (
    SELECT films.id, films.popularity FROM films, winner
    WHERE films.id <> $1
        AND films.rating BETWEEN winner.rating - $2::float
            AND winner.rating + $2::float
),
closest AS (
    SELECT films.id, films.popularity FROM films, winner
    WHERE films.id <> $1
    ORDER BY ABS(films.rating - winner.rating) LIMIT 40
),
random_id AS (
    -- Popularity-weighted random opponent within the rating window; if none,
    -- among the 40 closest. Exponential-clock sampling: P(i) ∝ weight, with a
    -- +1 baseline so popularity=0 films stay selectable (and avoid div by zero).
    -- popularity_weight scales the effect; 0 = uniform random selection.
    SELECT id FROM (
        SELECT id, popularity FROM in_window
        UNION ALL
        SELECT id, popularity FROM closest
        WHERE NOT EXISTS (SELECT 1 FROM in_window)
    ) AS candidates
    ORDER BY -LN(1.0 - RANDOM())
        / (1.0 + candidates.popularity * $3::float)
    LIMIT 1
),
inserted_duel AS (
    INSERT INTO duels (film_a_id, film_b_id)
    SELECT $1, random_id.id FROM random_id
    RETURNING duels.id AS duel_id, film_a_id, film_b_id
)
SELECT i.duel_id,
    fa.id AS film_a_id, fa.title AS film_a_title, fa.release_year AS film_a_release_year,
    fa.image_path AS film_a_image_path, fa.rating AS film_a_rating,
    da.id AS director_a_id, da.name AS director_a_name,
    fb.id AS film_b_id, fb.title AS film_b_title, fb.release_year AS film_b_release_year,
    fb.image_path AS film_b_image_path, fb.rating AS film_b_rating,
    db.id AS director_b_id, db.name AS director_b_name
FROM inserted_duel i
JOIN films fa ON fa.id = i.film_a_id JOIN directors da ON da.id = fa.director_id
JOIN films fb ON fb.id = i.film_b_id JOIN directors db ON db.id = fb.director_id
`

type ComposeDuelParams struct {
	WinnerID         int32
	RatingWindow     float64
	PopularityWeight float64
}

type ComposeDuelRow struct {
	DuelID           uuid.UUID
	FilmAID          int32
	FilmATitle       string
	FilmAReleaseYear int16
	FilmAImagePath   *string
	FilmARating      float64
	DirectorAID      int32
	DirectorAName    string
	FilmBID          int32
	FilmBTitle       string
	FilmBReleaseYear int16
	FilmBImagePath   *string
	FilmBRating      float64
	DirectorBID      int32
	DirectorBName    string
}

func (q *Queries) ComposeDuel(ctx context.Context, arg ComposeDuelParams) (ComposeDuelRow, error) {
	row := q.db.QueryRow(ctx, composeDuel, arg.WinnerID, arg.RatingWindow, arg.PopularityWeight)
	var i ComposeDuelRow
	err := row.Scan(
		&i.DuelID,
		&i.FilmAID,
		&i.FilmATitle,
		&i.FilmAReleaseYear,
		&i.FilmAImagePath,
		&i.FilmARating,
		&i.DirectorAID,
		&i.DirectorAName,
		&i.FilmBID,
		&i.FilmBTitle,
		&i.FilmBReleaseYear,
		&i.FilmBImagePath,
		&i.FilmBRating,
		&i.DirectorBID,
		&i.DirectorBName,
	)
	return i, err
}

const countPendingDuels = `-- name: CountPendingDuels :one
SELECT COUNT(*) FROM duels d
WHERE NOT EXISTS (SELECT 1 FROM votes v WHERE v.duel_id = d.id)
`

func (q *Queries) CountPendingDuels(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingDuels)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDuel = `-- name: CreateDuel :one
WITH inserted_duel AS (
    INSERT INTO duels (film_a_id, film_b_id)
    VALUES ($1, $2)
    RETURNING id AS duel_id, film_a_id, film_b_id
)
SELECT i.duel_id,
    fa.id AS film_a_id, fa.title AS film_a_title, fa.release_year AS film_a_release_year,
    fa.image_path AS film_a_image_path, fa.rating AS film_a_rating,
    da.id AS director_a_id, da.name AS director_a_name,
    fb.id AS film_b_id, fb.title AS film_b_title, fb.release_year AS film_b_release_year,
    fb.image_path AS film_b_image_path, fb.rating AS film_b_rating,
    db.id AS director_b_id, db.name AS director_b_name
FROM inserted_duel i
JOIN films fa ON fa.id = i.film_a_id JOIN directors da ON da.id = fa.director_id
JOIN films fb ON fb.id = i.film_b_id JOIN directors db ON db.id = fb.director_id
`

type CreateDuelParams struct {
	FilmAID int32
	FilmBID int32
}

type CreateDuelRow struct {
	DuelID           uuid.UUID
	FilmAID          int32
	FilmATitle       string
	FilmAReleaseYear int16
	FilmAImagePath   *string
	FilmARating      float64
	DirectorAID      int32
	DirectorAName    string
	FilmBID          int32
	FilmBTitle       string
	FilmBReleaseYear int16
	FilmBImagePath   *string
	FilmBRating      float64
	DirectorBID      int32
	DirectorBName    string
}

func (q *Queries) CreateDuel(ctx context.Context, arg CreateDuelParams) (CreateDuelRow, error) {
	row := q.db.QueryRow(ctx, createDuel, arg.FilmAID, arg.FilmBID)
	var i CreateDuelRow
	err := row.Scan(
		&i.DuelID,
		&i.FilmAID,
		&i.FilmATitle,
		&i.FilmAReleaseYear,
		&i.FilmAImagePath,
		&i.FilmARating,
		&i.DirectorAID,
		&i.DirectorAName,
		&i.FilmBID,
		&i.FilmBTitle,
		&i.FilmBReleaseYear,
		&i.FilmBImagePath,
		&i.FilmBRating,
		&i.DirectorBID,
		&i.DirectorBName,
	)
	return i, err
}

const findCandidates = `-- name: FindCandidates :many
WITH winner AS (
    SELECT rating FROM films WHERE films.id = $2
),
closest AS (
    SELECT films.id, films.popularity, films.duel_count, films.created_at,
        ABS(films.rating - winner.rating) <= $3::float AS in_window,
        ABS(films.rating - winner.rating) AS rating_distance
    FROM films, winner
    WHERE films.id <> $2
    ORDER BY ABS(films.rating - winner.rating)
    LIMIT $4::int
)
SELECT id, popularity, duel_count, created_at FROM closest
ORDER BY rating_distance
LIMIT GREATEST(
    (SELECT COUNT(*) FROM closest WHERE in_window),
    $1::int
)
`

type FindCandidatesParams struct {
	MinCandidates int32
	WinnerID      int32
	RatingWindow  float64
	MaxCandidates int32
}

type FindCandidatesRow struct {
	ID         int32
	Popularity float64
	DuelCount  int32
	CreatedAt  time.Time
}

func (q *Queries) FindCandidates(ctx context.Context, arg FindCandidatesParams) ([]FindCandidatesRow, error) {
	rows, err := q.db.Query(ctx, findCandidates,
		arg.MinCandidates,
		arg.WinnerID,
		arg.RatingWindow,
		arg.MaxCandidates,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindCandidatesRow
	for rows.Next() {
		var i FindCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Popularity,
			&i.DuelCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDuelFilms = `-- name: GetDuelFilms :many
SELECT films.id, films.title, films.release_year, films.image_path, films.rating,
    directors.id AS director_id, directors.name AS director_name
FROM films
JOIN directors ON films.director_id = directors.id
WHERE films.id IN (
    SELECT film_a_id FROM duels WHERE duels.id = $1
    UNION
    SELECT film_b_id FROM duels WHERE duels.id = $1
)
`

type GetDuelFilmsRow struct {
	ID           int32
	Title        string
	ReleaseYear  int16
	ImagePath    *string
	Rating       float64
	DirectorID   int32
	DirectorName string
}

func (q *Queries) GetDuelFilms(ctx context.Context, id uuid.UUID) ([]GetDuelFilmsRow, error) {
	rows, err := q.db.Query(ctx, getDuelFilms, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDuelFilmsRow
	for rows.Next() {
		var i GetDuelFilmsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ReleaseYear,
			&i.ImagePath,
			&i.Rating,
			&i.DirectorID,
			&i.DirectorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDuelRatingsForUpdate = `-- name: GetDuelRatingsForUpdate :many
SELECT id, rating, duel_count
FROM films
WHERE films.id IN (
    SELECT film_a_id FROM duels WHERE duels.id = $1
    UNION
    SELECT film_b_id FROM duels WHERE duels.id = $1
)
ORDER BY films.id
FOR UPDATE
`

type GetDuelRatingsForUpdateRow struct {
	ID        int32
	Rating    float64
	DuelCount int32
}

func (q *Queries) GetDuelRatingsForUpdate(ctx context.Context, id uuid.UUID) ([]GetDuelRatingsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, getDuelRatingsForUpdate, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDuelRatingsForUpdateRow
	for rows.Next() {
		var i GetDuelRatingsForUpdateRow
		if err := rows.Scan(&i.ID, &i.Rating, &i.DuelCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDuel = `-- name: InsertDuel :one
INSERT INTO duels (film_a_id, film_b_id)
VALUES ($1, $2)
RETURNING id
`

type InsertDuelParams struct {
	FilmAID int32
	FilmBID int32
}

func (q *Queries) InsertDuel(ctx context.Context, arg InsertDuelParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertDuel, arg.FilmAID, arg.FilmBID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const selectRandomFilms = `-- name: SelectRandomFilms :many
SELECT films.id, films.title, films.release_year, films.image_path, films.rating,
    directors.id AS director_id, directors.name AS director_name
FROM films
JOIN directors ON films.director_id = directors.id
ORDER BY RANDOM() LIMIT 2
`

type SelectRandomFilmsRow struct {
	ID           int32
	Title        string
	ReleaseYear  int16
	ImagePath    *string
	Rating       float64
	DirectorID   int32
	DirectorName string
}

func (q *Queries) SelectRandomFilms(ctx context.Context) ([]SelectRandomFilmsRow, error) {
	rows, err := q.db.Query(ctx, selectRandomFilms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectRandomFilmsRow
	for rows.Next() {
		var i SelectRandomFilmsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ReleaseYear,
			&i.ImagePath,
			&i.Rating,
			&i.DirectorID,
			&i.DirectorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
