// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: films.sql

package dbgen

import (
	"context"
)

const countFilms = `-- name: CountFilms :one
SELECT COUNT(*) FROM films
`

func (q *Queries) CountFilms(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFilms)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDirector = `-- name: GetDirector :one
SELECT id, name FROM directors WHERE id = $1
`

func (q *Queries) GetDirector(ctx context.Context, id int32) (Director, error) {
	row := q.db.QueryRow(ctx, getDirector, id)
	var i Director
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getFilm = `-- name: GetFilm :one
SELECT films.id, films.title, films.release_year, films.image_path, films.rating,
    directors.id AS director_id, directors.name AS director_name
FROM films
JOIN directors ON films.director_id = directors.id
WHERE films.id = $1
`

type GetFilmRow struct {
	ID           int32
	Title        string
	ReleaseYear  int16
	ImagePath    *string
	Rating       float64
	DirectorID   int32
	DirectorName string
}

func (q *Queries) GetFilm(ctx context.Context, id int32) (GetFilmRow, error) {
	row := q.db.QueryRow(ctx, getFilm, id)
	var i GetFilmRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ReleaseYear,
		&i.ImagePath,
		&i.Rating,
		&i.DirectorID,
		&i.DirectorName,
	)
	return i, err
}

const getRandomFilm = `-- name: GetRandomFilm :one
SELECT films.id, films.title, films.release_year, films.image_path, films.rating,
    directors.id AS director_id, directors.name AS director_name
FROM films
JOIN directors ON films.director_id = directors.id
ORDER BY RANDOM() LIMIT 1
`

type GetRandomFilmRow struct {
	ID           int32
	Title        string
	ReleaseYear  int16
	ImagePath    *string
	Rating       float64
	DirectorID   int32
	DirectorName string
}

func (q *Queries) GetRandomFilm(ctx context.Context) (GetRandomFilmRow, error) {
	row := q.db.QueryRow(ctx, getRandomFilm)
	var i GetRandomFilmRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ReleaseYear,
		&i.ImagePath,
		&i.Rating,
		&i.DirectorID,
		&i.DirectorName,
	)
	return i, err
}

const insertDirector = `-- name: InsertDirector :one
INSERT INTO directors (id, name)
VALUES ($1, $2)
RETURNING id
`

type InsertDirectorParams struct {
	ID   int32
	Name string
}

func (q *Queries) InsertDirector(ctx context.Context, arg InsertDirectorParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertDirector, arg.ID, arg.Name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertFilm = `-- name: InsertFilm :one
WITH new_director AS (
    INSERT INTO directors (id, name)
    VALUES ($6, $7)
    ON CONFLICT DO NOTHING
    RETURNING id AS director_id
),
director AS (
    SELECT director_id FROM new_director
    UNION ALL
    SELECT id AS director_id FROM directors WHERE id = $6
)
INSERT INTO films (id, title, release_year, director_id, image_path, rating)
SELECT $1, $2, $3, director_id, $4, $5 FROM director
RETURNING id
`

type InsertFilmParams struct {
	ID           int32
	Title        string
	ReleaseYear  int16
	ImagePath    *string
	Rating       float64
	DirectorID   int32
	DirectorName string
}

func (q *Queries) InsertFilm(ctx context.Context, arg InsertFilmParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertFilm,
		arg.ID,
		arg.Title,
		arg.ReleaseYear,
		arg.ImagePath,
		arg.Rating,
		arg.DirectorID,
		arg.DirectorName,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const listFilmsByRating = `-- name: ListFilmsByRating :many
SELECT films.id, films.title, films.release_year, films.image_path, films.rating,
    directors.id AS director_id, directors.name AS director_name
FROM films
JOIN directors ON films.director_id = directors.id
WHERE (
    $2::int IS NULL
    OR (films.rating, films.id) < ($3::float, $2::int)
)
ORDER BY films.rating DESC, films.id DESC
LIMIT $1
`

type ListFilmsByRatingParams struct {
	Limit          int32
	LastSeenID     *int32
	LastSeenRating *float64
}

type ListFilmsByRatingRow struct {
	ID           int32
	Title        string
	ReleaseYear  int16
	ImagePath    *string
	Rating       float64
	DirectorID   int32
	DirectorName string
}

func (q *Queries) ListFilmsByRating(ctx context.Context, arg ListFilmsByRatingParams) ([]ListFilmsByRatingRow, error) {
	rows, err := q.db.Query(ctx, listFilmsByRating, arg.Limit, arg.LastSeenID, arg.LastSeenRating)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilmsByRatingRow
	for rows.Next() {
		var i ListFilmsByRatingRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ReleaseYear,
			&i.ImagePath,
			&i.Rating,
			&i.DirectorID,
			&i.DirectorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFilmsByTitle = `-- name: SearchFilmsByTitle :many
SELECT films.id, films.title, films.release_year, films.image_path, films.rating,
    directors.id AS director_id, directors.name AS director_name
FROM films
JOIN directors ON films.director_id = directors.id
WHERE films.title ILIKE '%' || $1::text || '%'
`

type SearchFilmsByTitleRow struct {
	ID           int32
	Title        string
	ReleaseYear  int16
	ImagePath    *string
	Rating       float64
	DirectorID   int32
	DirectorName string
}

func (q *Queries) SearchFilmsByTitle(ctx context.Context, search string) ([]SearchFilmsByTitleRow, error) {
	rows, err := q.db.Query(ctx, searchFilmsByTitle, search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchFilmsByTitleRow
	for rows.Next() {
		var i SearchFilmsByTitleRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ReleaseYear,
			&i.ImagePath,
			&i.Rating,
			&i.DirectorID,
			&i.DirectorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFilmRating = `-- name: UpdateFilmRating :execrows
UPDATE films SET rating = $1 WHERE id = $2
`

type UpdateFilmRatingParams struct {
	Rating float64
	ID     int32
}

func (q *Queries) UpdateFilmRating(ctx context.Context, arg UpdateFilmRatingParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFilmRating, arg.Rating, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
