// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: freezeframe.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAnswer = `-- name: InsertAnswer :one
INSERT INTO answers(reel_id, reel_alternative_id, user_id, frames_revealed)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertAnswerParams struct {
	ReelID            int32
	ReelAlternativeID int32
	UserID            uuid.UUID
	FramesRevealed    int16
}

func (q *Queries) InsertAnswer(ctx context.Context, arg InsertAnswerParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertAnswer,
		arg.ReelID,
		arg.ReelAlternativeID,
		arg.UserID,
		arg.FramesRevealed,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertGame = `-- name: InsertGame :one
INSERT INTO games (valid_at)
VALUES ($1)
RETURNING id
`

func (q *Queries) InsertGame(ctx context.Context, validAt pgtype.Date) (int32, error) {
	row := q.db.QueryRow(ctx, insertGame, validAt)
	var id int32
	err := row.Scan(&id)
	return id, err
}
