// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type Director struct {
	ID   int32
	Name string
}

type Duel struct {
	ID        uuid.UUID
	FilmAID   int32
	FilmBID   int32
	CreatedAt time.Time
}

type Film struct {
	ID          int32
	Title       string
	ReleaseYear int16
	DirectorID  int32
	ImagePath   *string
	Rating      float64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Session struct {
	ID                   uuid.UUID
	TokenHash            []byte
	UserID               uuid.UUID
	AccessToken          []byte
	AccessTokenExpiresAt *time.Time
	RefreshToken         []byte
	IDToken              []byte
	Scopes               *string
	IPAddress            netip.Addr
	UserAgent            *string
	Roles                []string
	CreatedAt            time.Time
	LastSeenAt           time.Time
	ExpiresAt            time.Time
}

type SessionEvent struct {
	ID        int64
	SessionID uuid.UUID
	IdpSub    string
	Event     string
	IPAddress netip.Addr
	CreatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	IdpSub    string
	CreatedAt time.Time
}

type Vote struct {
	ID                uuid.UUID
	DuelID            uuid.UUID
	WinnerID          int32
	LoserID           int32
	WinnerRatingAfter float64
	LoserRatingAfter  float64
	AppliedSeq        int64
	UserID            *uuid.UUID
	CreatedAt         time.Time
}
