// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Answer struct {
	ID                int32
	ReelID            int32
	ReelAlternativeID int32
	UserID            uuid.UUID
	FramesRevealed    int16
	CreatedAt         time.Time
}

type Director struct {
	ID   int32
	Name string
}

type Duel struct {
	ID        uuid.UUID
	FilmAID   int32
	FilmBID   int32
	CreatedAt time.Time
}

type Film struct {
	ID          int32
	Title       string
	ReleaseYear int16
	DirectorID  int32
	ImagePath   *string
	Popularity  float64
	VoteAverage float64
	Rating      float64
	DuelCount   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Frame struct {
	ID        int32
	FilmID    int32
	ImagePath string
	CreatedAt time.Time
}

type Game struct {
	ID        int32
	ValidAt   pgtype.Date
	CreatedAt time.Time
}

type Reel struct {
	ID        int32
	GameID    int32
	FilmID    int32
	Seq       int16
	CreatedAt time.Time
}

type ReelAlternative struct {
	ID        int32
	ReelID    int32
	FilmID    int32
	Seq       int16
	CreatedAt time.Time
}

type ReelFrame struct {
	ID         int32
	ReelID     int32
	FrameID    int32
	Difficulty int16
	Seq        int16
}

type Session struct {
	ID                   uuid.UUID
	TokenHash            []byte
	UserID               uuid.UUID
	AccessToken          []byte
	AccessTokenExpiresAt *time.Time
	RefreshToken         []byte
	IDToken              []byte
	Scopes               *string
	IPAddress            netip.Addr
	UserAgent            *string
	Roles                []string
	CreatedAt            time.Time
	LastSeenAt           time.Time
	ExpiresAt            time.Time
}

type SessionEvent struct {
	ID        int64
	SessionID uuid.UUID
	PidSub    string
	Event     string
	IPAddress netip.Addr
	CreatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	PidSub    string
	CreatedAt time.Time
}

type Vote struct {
	ID                uuid.UUID
	DuelID            uuid.UUID
	WinnerID          int32
	LoserID           int32
	WinnerRatingAfter float64
	LoserRatingAfter  float64
	AppliedSeq        int64
	UserID            *uuid.UUID
	CreatedAt         time.Time
}
