// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: placeholder.sql

package database

import (
	"context"
)

const ping = `-- name: Ping :one

SELECT 1 AS ping
`

// Placeholder so sqlc can generate models from the schema.
// Delete this file once real queries are added.
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ping int32
	err := row.Scan(&ping)
	return ping, err
}
