// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: votes.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countVotes = `-- name: CountVotes :one
SELECT COUNT(*) FROM votes
`

func (q *Queries) CountVotes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countVotes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertVote = `-- name: InsertVote :one
INSERT INTO votes (duel_id, user_id, winner_id, loser_id, winner_rating_after, loser_rating_after)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertVoteParams struct {
	DuelID            uuid.UUID
	UserID            *uuid.UUID
	WinnerID          int32
	LoserID           int32
	WinnerRatingAfter float64
	LoserRatingAfter  float64
}

func (q *Queries) InsertVote(ctx context.Context, arg InsertVoteParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertVote,
		arg.DuelID,
		arg.UserID,
		arg.WinnerID,
		arg.LoserID,
		arg.WinnerRatingAfter,
		arg.LoserRatingAfter,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listFilmVotes = `-- name: ListFilmVotes :many
SELECT v.winner_id, v.loser_id, v.winner_rating_after, v.loser_rating_after, v.created_at,
    fw.title AS winner_title, fw.release_year AS winner_release_year,
    fl.title AS loser_title, fl.release_year AS loser_release_year
FROM votes v
JOIN films fw ON fw.id = v.winner_id
JOIN films fl ON fl.id = v.loser_id
WHERE v.winner_id = $1 OR v.loser_id = $1
ORDER BY v.created_at DESC
`

type ListFilmVotesRow struct {
	WinnerID          int32
	LoserID           int32
	WinnerRatingAfter float64
	LoserRatingAfter  float64
	CreatedAt         time.Time
	WinnerTitle       string
	WinnerReleaseYear int16
	LoserTitle        string
	LoserReleaseYear  int16
}

func (q *Queries) ListFilmVotes(ctx context.Context, winnerID int32) ([]ListFilmVotesRow, error) {
	rows, err := q.db.Query(ctx, listFilmVotes, winnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilmVotesRow
	for rows.Next() {
		var i ListFilmVotesRow
		if err := rows.Scan(
			&i.WinnerID,
			&i.LoserID,
			&i.WinnerRatingAfter,
			&i.LoserRatingAfter,
			&i.CreatedAt,
			&i.WinnerTitle,
			&i.WinnerReleaseYear,
			&i.LoserTitle,
			&i.LoserReleaseYear,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserVotes = `-- name: ListUserVotes :many
SELECT v.winner_id, v.loser_id, v.winner_rating_after, v.loser_rating_after, v.created_at,
    fw.title AS winner_title, fw.release_year AS winner_release_year, fw.image_path AS winner_image_path,
    fl.title AS loser_title, fl.release_year AS loser_release_year, fl.image_path AS loser_image_path
FROM votes v
JOIN films fw ON fw.id = v.winner_id
JOIN films fl ON fl.id = v.loser_id
WHERE v.user_id = $1
ORDER BY v.created_at DESC
`

type ListUserVotesRow struct {
	WinnerID          int32
	LoserID           int32
	WinnerRatingAfter float64
	LoserRatingAfter  float64
	CreatedAt         time.Time
	WinnerTitle       string
	WinnerReleaseYear int16
	WinnerImagePath   *string
	LoserTitle        string
	LoserReleaseYear  int16
	LoserImagePath    *string
}

func (q *Queries) ListUserVotes(ctx context.Context, userID *uuid.UUID) ([]ListUserVotesRow, error) {
	rows, err := q.db.Query(ctx, listUserVotes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserVotesRow
	for rows.Next() {
		var i ListUserVotesRow
		if err := rows.Scan(
			&i.WinnerID,
			&i.LoserID,
			&i.WinnerRatingAfter,
			&i.LoserRatingAfter,
			&i.CreatedAt,
			&i.WinnerTitle,
			&i.WinnerReleaseYear,
			&i.WinnerImagePath,
			&i.LoserTitle,
			&i.LoserReleaseYear,
			&i.LoserImagePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
